### ISSUE TITLE
License Violation – Please Comply with Apache 2.0 Terms

### ISSUE THREAD

**Issue by sharkadi-a** [Latency/JsonEasyNavigation#1]
Hi,

I’m the original author of the project you forked (https://github.com/sharkadi-a/JsonEasyNavigation), and I noticed that the license for the fork has been changed from Apache License 2.0 to MIT. In addition, your fork lists you as the sole author, and donations are being collected without attribution to the original project or authors.

According to the terms of the Apache License 2.0, it is essential that:

* The original license is retained.
* Proper credit is given to the original author(s).
* Changes to the original work are clearly noted.

I kindly ask that you:

* Reapply the Apache License 2.0 to your forked repository.
* Include proper attribution to me as the original author and reference the original project.
* Remove the donations link associated with this work.

If you prefer not to comply with the licensing terms, I respectfully ask that you remove the repository from your GitHub profile.

I appreciate your understanding and cooperation.

**Comment by Latency** [comment]
Updated!
